language: python

matrix:
  include:
    - os: linux
      python: 2.7
      env: PYTHON_VERSION=2.7

    - os: linux
      python: 3.6
      env: PYTHON_VERSION=3.6

      #- os: osx
      #- python: 2.7
      #- language: generic
      #- env: PYTHON_VERSION=2.7

    - #- os: osx
      #- python: 3.6
      #- language: generic
      #- env: PYTHON_VERSION=3.6

install:
  - env

  # Install conda https://conda.io/docs/travis.html
  - source scripts/conda_get.sh
  - scripts/conda_runtests.sh

  # Install with pip and wheels
  - scripts/pip_runtests.sh

before_script:
    # https://github.com/travis-ci/travis-ci/issues/6307
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then rvm get head; fi 

# command to run tests
script: true

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always
