language: python

# We don't actually use the Travis Python but conda
matrix:
  include:
    - os: linux
      python: 2.7
      env: PYTHON_VERSION=2.7

    - os: linux
      python: 3.6
      env: PYTHON_VERSION=3.6
    - os: osx
      python: 2.7
      language: generic
      env: PYTHON_VERSION=2.7
    - os: osx
      python: 3.6
      language: generic
      env: PYTHON_VERSION=3.6

install:
  - env

  # Install with pip and wheels
  - scripts/install_with_pip.sh

  # Install conda https://conda.io/docs/travis.html
  - source scripts/conda_installer.sh
  - scripts/install_with_conda.sh

before_script:
    # https://github.com/travis-ci/travis-ci/issues/6307
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then rvm get head; fi 

# command to run tests
script: true

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always
