language: python
cache: pip

#dist: precise
sudo: false

env:
  global:
    - ABINIT_VERSION=8.10.1
    - ABIPY_PYTEST=yes
    - OPENBLAS_NUM_THREADS=1
    - OMP_NUM_THREADS=1

matrix:
  include:
    - os: linux
      python: 3.6
      env:
        - ABIPY_INSTALLER=conda
    - os: linux
      python: 3.6
      sudo: true
      env:
        - ABIPY_INSTALLER=pip
    - os: linux
      python: 3.7
      env:
        - ABIPY_INSTALLER=conda
    - os: linux
      python: 3.7
      sudo: true
      env:
        - ABIPY_INSTALLER=pip

install:
  - env
  - |
      if [ "${ABIPY_INSTALLER}" == "conda" ]; then
        # Install with conda https://conda.io/docs/travis.html
        source scripts/conda_get.sh
        source scripts/conda_runtests.sh
      elif [ "${ABIPY_INSTALLER}" == "pip" ]; then
        # Install with pip and wheels
        travis_wait scripts/pip_runtests.sh
      fi

before_script:
    # https://github.com/travis-ci/travis-ci/issues/6307
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then rvm get head; fi

# command to run tests
script: true

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always
